name: Release

on:
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: release
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge changes from main
        run: |
          git merge origin/main -m "chore: new release" || {
            echo "Merge conflict occurred while merging main into release branch."
            exit 1
          }

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Commit changes to release branch
        id: commit
        run: |
          git add --force dist/index.js
          if git diff --staged --quiet; then
            echo "No changes. Skipping."
          else
            echo has_changes=true >> $GITHUB_OUTPUT
          fi

      - name: Update GitHub Release
        id: release
        if: steps.commit.outputs.has_changes == 'true'
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # We're using a dedicated branch for the releases code in `dist`
          target-branch: main

      - name: Push release branch
        if: |
          steps.commit.outputs.has_changes == 'true' &&
            (steps.release.outputs.action == 'created' || steps.release.outputs.action == 'updated')
        run: |
          git commit --amend --message "chore: release v${{ steps.release.outputs.next-version }}"
          git push origin release
